defaults:
  - _self_ 
  - model: playground
  - training: playground
  - logging: basic
  - data: faceforensics

hydra:
  job:
    chdir: true
  run:
    dir: ./experiments/${model.model_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}