defaults:
- _self_
- common
- model: dual_branch_attention
- training: base
model:
  classifier_head:
    name: dual_branch_v2
  dropout: 0.4
  init_weights_method: kaiming
  name: dual_branch_attention_v6
training:
  learning_rate: 0.0001
  max_epochs: 25
  scheduler:
    cosine_T_max: 25
    type: CosineAnnealingLR
