defaults:
  - _self_ 
  - common
  - model: transformer
  - training: base

model:
  name: transformer_v1
  dropout: 0.3

training:
  learning_rate: 1e-4
  max_epochs: 20
  scheduler_type: CosineAnnealingLR
  cosine_T_max: 20
