accelerator: cpu

early_stopping:
  use: true
  patience: 4

# Parameters exampled values
# learning_rate: 1e-4
# max_epochs: 20

# scheduler:
#   type: CosineAnnealingLR
#   cosine_T_max: 20
# 
# scheduler:
#   type: ReduceLROnPlateau
#   decay_factor: 0.8
#   monitor: val_loss